[package]
name = "arc114"
version = "0.1.0"
authors = ["naca-nyan <naca.nyan@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
num = "0.4.0"
proconio = "0.4.1"

[profile.release]
lto = true
panic = 'abort'
